"""empty message

Revision ID: cc02f8f7ef42
Revises: d33a1079426d
Create Date: 2022-11-02 21:02:44.875847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc02f8f7ef42'
down_revision = 'd33a1079426d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('film_genres',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], )
    )
    op.add_column('actors', sa.Column('photo_url', sa.String(length=500), nullable=False))
    op.add_column('actors', sa.Column('bio', sa.String(length=2000), nullable=True))
    op.drop_column('actors', 'photo')
    op.add_column('films', sa.Column('photo_url', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'photo_url')
    op.add_column('actors', sa.Column('photo', sa.VARCHAR(length=500), nullable=False))
    op.drop_column('actors', 'bio')
    op.drop_column('actors', 'photo_url')
    op.drop_table('film_genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
