"""empty message

Revision ID: 73bb9742ff94
Revises: 9b5eff972f0b
Create Date: 2022-12-06 15:48:20.671125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bb9742ff94'
down_revision = '9b5eff972f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('image_url', sa.String(length=1000), nullable=False))
    op.drop_column('films', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('photo_url', sa.VARCHAR(length=1000), nullable=False))
    op.drop_column('films', 'image_url')
    # ### end Alembic commands ###
