"""empty message

Revision ID: a46a27d82e7e
Revises: 73bb9742ff94
Create Date: 2022-12-06 19:39:57.582037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46a27d82e7e'
down_revision = '73bb9742ff94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('photo_url', sa.String(length=1000), nullable=False))
    op.drop_column('films', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('image_url', sa.VARCHAR(length=1000), nullable=False))
    op.drop_column('films', 'photo_url')
    # ### end Alembic commands ###
